sonar.projectKey=2025-itcs383-emerald_2025-itcs383-emerald
sonar.organization=2025-ITCS383-Emerald


sonar.sources=.
sonar.exclusions=node_modules/**,public/**/*.css,public/**/*.html,coverage/**,.github/**
sonar.javascript.file.suffixes=.js
sonar.sourceEncoding=UTF-8
