version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # เชื่อมต่อกับไฟล์ database.sqlite ที่เพื่อน Backend ทำไว้
    restart: always